In [1]:
import pandas as pd

In [2]:
items = pd.read_csv("../data/items.csv")
users = pd.read_csv("../data/users.csv")

In [3]:
print("Items Dataset Shape:", items.shape)
print("Users Dataset Shape:", users.shape)

Items Dataset Shape: (100, 6)
Users Dataset Shape: (20, 5)

In [4]:
print("Items Columns:")
print(items.columns.tolist())

print("\nUsers Columns:")
print(users.columns.tolist())

Items Columns:
['Item_ID', 'Item_Name', 'Category', 'Genre', 'Tags', 'Rating']

Users Columns:
['User_ID', 'User_Name', 'Preferred_Category', 'Preferred_Genre', 'Preferred_Tags']

In [5]:
print("Items Missing Values:")
print(items.isnull().sum())

print("\nUsers Missing Values:")
print(users.isnull().sum())

Items Missing Values:
Item_ID      0
Item_Name    0
Category     0
Genre        0
Tags         0
Rating       0
dtype: int64

Users Missing Values:
User_ID               0
User_Name             0
Preferred_Category    0
Preferred_Genre       0
Preferred_Tags        0
dtype: int64

In [6]:
print("Duplicate item rows:", items.duplicated().sum())
print("Duplicate user rows:", users.duplicated().sum())

Duplicate item rows: 0
Duplicate user rows: 0

In [7]:
print("Duplicate Item IDs:", items["Item_ID"].duplicated().sum())
print("Duplicate User IDs:", users["User_ID"].duplicated().sum())

Duplicate Item IDs: 0
Duplicate User IDs: 0

In [8]:
print("Items Data Types:")
print(items.dtypes)

print("\nUsers Data Types:")
print(users.dtypes)

Items Data Types:
Item_ID          str
Item_Name        str
Category         str
Genre            str
Tags             str
Rating       float64
dtype: object

Users Data Types:
User_ID               str
User_Name             str
Preferred_Category    str
Preferred_Genre       str
Preferred_Tags        str
dtype: object

In [9]:
invalid_ratings = items[
    (items["Rating"] < 5.0) |
    (items["Rating"] > 9.5)
]

print("Invalid Ratings:")
print(invalid_ratings)

Invalid Ratings:
Empty DataFrame
Columns: [Item_ID, Item_Name, Category, Genre, Tags, Rating]
Index: []

In [10]:
invalid_categories = items[items["Category"] != "Movie"]

print("Invalid Item Categories:")
print(invalid_categories)

Invalid Item Categories:
Empty DataFrame
Columns: [Item_ID, Item_Name, Category, Genre, Tags, Rating]
Index: []

In [11]:
invalid_user_categories = users[
    users["Preferred_Category"] != "Movie"
]

print("Invalid User Categories:")
print(invalid_user_categories)

Invalid User Categories:
Empty DataFrame
Columns: [User_ID, User_Name, Preferred_Category, Preferred_Genre, Preferred_Tags]
Index: []

In [12]:
print("===== DATASET VALIDATION SUMMARY =====")

print("Items shape:", items.shape)
print("Users shape:", users.shape)

print("Missing item values:", items.isnull().sum().sum())
print("Missing user values:", users.isnull().sum().sum())

print("Duplicate item rows:", items.duplicated().sum())
print("Duplicate user rows:", users.duplicated().sum())

print("Duplicate Item IDs:", items["Item_ID"].duplicated().sum())
print("Duplicate User IDs:", users["User_ID"].duplicated().sum())

print(
    "Invalid ratings:",
    ((items["Rating"] < 5.0) | (items["Rating"] > 9.5)).sum()
)

print(
    "Invalid item categories:",
    (items["Category"] != "Movie").sum()
)

print(
    "Invalid user categories:",
    (users["Preferred_Category"] != "Movie").sum()
)

===== DATASET VALIDATION SUMMARY =====
Items shape: (100, 6)
Users shape: (20, 5)
Missing item values: 0
Missing user values: 0
Duplicate item rows: 0
Duplicate user rows: 0
Duplicate Item IDs: 0
Duplicate User IDs: 0
Invalid ratings: 0
Invalid item categories: 0
Invalid user categories: 0

In [2]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

from src.data_loader import load_items, load_users

In [3]:
items = load_items()
users = load_users()

In [4]:
print("Items data type:", type(items))
print("Users data type:", type(users))

Items data type: <class 'pandas.DataFrame'>
Users data type: <class 'pandas.DataFrame'>

In [5]:
print("Items Dataset Shape:", items.shape)
print("Users Dataset Shape:", users.shape)

Items Dataset Shape: (100, 6)
Users Dataset Shape: (20, 5)

In [6]:
print("Items Dataset:")
display(items.head())

print("Users Dataset:")
display(users.head())

Items Dataset:

,Item_ID,Item_Name,Category,Genre,Tags,Rating
0,M001,Inception,Movie,Sci-Fi,"Dreams, Mind, Technology, Mystery, Heist",8.8
1,M002,The Dark Knight,Movie,Action,"Hero, Crime, Vigilante, Justice, Chaos",9.0
2,M003,Interstellar,Movie,Sci-Fi,"Space, Black Hole, Time, Exploration, Survival",8.7
3,M004,The Matrix,Movie,Sci-Fi,"AI, Cyberpunk, Virtual Reality, Action, Dystopia",8.7
4,M005,Pulp Fiction,Movie,Crime,"Gangster, Nonlinear, Dialogue, Humor, Mob",8.9

Users Dataset:

,User_ID,User_Name,Preferred_Category,Preferred_Genre,Preferred_Tags
0,U001,Alex,Movie,Sci-Fi,"AI, Technology, Future"
1,U002,Sophia,Movie,Romance,"Love, Emotional, Relationships"
2,U003,Daniel,Movie,Crime,"Detective, Mystery, Investigation"
3,U004,Emma,Movie,Fantasy,"Magic, Adventure, Kingdom"
4,U005,Michael,Movie,Action,"Superheroes, Adventure, Hero"

In [ ]:
assert items is not None
assert users is not None

assert not items.empty
assert not users.empty

assert items.shape == (100, 6)
assert users.shape == (20, 5)

print("✅ Items dataset loaded successfully.")
print("✅ Users dataset loaded successfully.")
print("✅ Dataset dimensions are correct.")
print("✅ Data loading test passed successfully!")